# Makefile for pure data class soundtouch~
lib.name := soundtouch

soundtouch~.class.sources := \
AAFilter.cpp \
cpu_detect_x86_gcc.cpp \
mmx_optimized.cpp \
FIFOSampleBuffer.cpp \
RateTransposer.cpp \
FIRFilter.cpp \
sse_optimized.cpp \
TDStretch.cpp \
SoundTouch.cpp \
soundtouch~.cpp

cflags := -I ./include

include Makefile.pdlibbuilder
